# Generated by Django 3.2.3 on 2021-06-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_topic_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['creation_time']},
        ),
    ]
