# Generated by Django 3.2.3 on 2021-06-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('board', 'subject')},
        ),
    ]
